import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//////////// Layout imports
import AppSidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased md:grid bg-[var(--bg)]  md:grid-cols-12`}
      >
        <div className="md:col-span-3  md:row-span-12  min-h-screen md:static fixed z-50">
          <AppSidebar />
        </div>
        <div className="md:col-span-9 w-full md:row-span-2">
          <Navbar />
        </div>
        <div
          className="min-h-[80dvh] md:row-span-10 md:col-start-4 md:col-span-9 w-full"
        >
          {children}
        </div>

        <Toaster />
      </body>
    </html>
  );
}
